name: Push-to-EC2

# Trigger deployment only on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Flask App to EC2
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout the files
        uses: actions/checkout@v2

      # Step 2: Deploy application files to the server
      - name: Deploy application files to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      # Step 3: Setup and start the Flask application on Amazon Linux
      - name: Configure and run Flask application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo yum update -y
            sudo yum install -y python3 python3-pip
            cd ${{ secrets.TARGET_DIR }}
            pip3 install -r requirements.txt
            # Ensure Flask server is accessible publicly
            export FLASK_APP=app.py
            nohup flask run --host=0.0.0.0 --port=5000 &
