name: Deploy Flask App to EC2

# Trigger deployment only on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # Copy files to EC2 server
      - name: Deploy Flask app to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }} << 'EOF'
            # Update and install necessary packages
            sudo apt-get update -y
            sudo apt-get install -y python3 python3-pip apache2 libapache2-mod-wsgi-py3

            # Navigate to the app directory
            cd /var/www/html

            # Remove any old files and copy new ones from GitHub repository
            sudo rm -rf *
            git clone https://github.com/${{ github.repository }} /var/www/html

            # Install dependencies
            if [ -f "requirements.txt" ]; then
              sudo pip3 install -r requirements.txt
            fi

            # Restart Apache to apply changes
            sudo systemctl restart apache2
          EOF

      # Verify deployment (Optional)
      #- name: Verify Flask app is running
        #run: |
          #ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.HOST_DNS }} << 'EOF'
            #curl -f http://localhost:80 || exit 1
          #EOF

